version: '3.8'

services:
  app-mapas:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-mapas-prod
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app-mapas.rule=Host(`your-domain.com`)"
      - "traefik.http.services.app-mapas.loadbalancer.server.port=80"

