// Runtime environment configuration
// Este archivo se genera dinámicamente por Docker
window.ENV = {
  VITE_MAPBOX_ACCESS_TOKEN: '${VITE_MAPBOX_ACCESS_TOKEN}',
  VITE_SUPABASE_URL: '${VITE_SUPABASE_URL}',
  VITE_SUPABASE_ANON_KEY: '${VITE_SUPABASE_ANON_KEY}',
  VITE_XAI_API_KEY: '${VITE_XAI_API_KEY}',
  VITE_X_API_KEY: '${VITE_X_API_KEY}',
  VITE_X_API_SECRET: '${VITE_X_API_SECRET}',
  VITE_APP_NAME: '${VITE_APP_NAME}',
  VITE_APP_VERSION: '${VITE_APP_VERSION}',
  VITE_MAP_CENTER_LAT: '${VITE_MAP_CENTER_LAT}',
  VITE_MAP_CENTER_LNG: '${VITE_MAP_CENTER_LNG}',
  VITE_MAP_DEFAULT_ZOOM: '${VITE_MAP_DEFAULT_ZOOM}'
};

