// Runtime environment configuration
// Este archivo se genera dinámicamente por Docker
window.ENV = {
  VITE_MAPBOX_ACCESS_TOKEN: '__VITE_MAPBOX_ACCESS_TOKEN__',
  VITE_SUPABASE_URL: '__VITE_SUPABASE_URL__',
  VITE_SUPABASE_ANON_KEY: '__VITE_SUPABASE_ANON_KEY__',
  VITE_XAI_API_KEY: '__VITE_XAI_API_KEY__',
  VITE_X_API_KEY: '__VITE_X_API_KEY__',
  VITE_X_API_SECRET: '__VITE_X_API_SECRET__',
  VITE_APP_NAME: '__VITE_APP_NAME__',
  VITE_APP_VERSION: '__VITE_APP_VERSION__',
  VITE_MAP_CENTER_LAT: '__VITE_MAP_CENTER_LAT__',
  VITE_MAP_CENTER_LNG: '__VITE_MAP_CENTER_LNG__',
  VITE_MAP_DEFAULT_ZOOM: '__VITE_MAP_DEFAULT_ZOOM__'
};

